// SIGN UP A NEW USER
POST http://localhost:3000/api/v1/users/sign-up
Content-Type: application/json

{
    "firstName": "naomi",
    "lastName": "adejare",
    "username": "nat",
    "email": "adejare345@gmail.com",
    "password": "Adejare.544$$"
}

// CHANGE USER PASSWORD
POST http://localhost:3000/api/v1/users/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNjIwZjY1Yi03Yzk5LTQzZGYtYjNkNi0wMDdmMGIzMmJmY2UiLCJlbWFpbCI6Im5pY2VtYW5AZ21haWwuY29tIiwiaWF0IjoxNzQ0Mjg1ODYxLCJleHAiOjE3NDQyODk0NjEsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMCJ9.w9P9d0YL9-rdefkyhBDMVz6Q9ao1RyCmhhgC9hUTCsc

{
    "currentPassword": "Mainmainceh63dfuer76f$ferf",
    "newPassword": "Mai6473h63dfuer76f$ferf"
}

// CREATE MANY USERS
POST http://localhost:3000/api/v1/users/create-multiple
Content-Type: application/json

{
    "users": [
        {
    "firstName": "fada",
    "lastName": "fedi",
    "email": "hedwej@gmail.com",
    "password": "Adejare.544$$"
},
 {
    "firstName": "remi",
    "lastName": "dasw",
    "email": "fwef@gmail.com",
    "password": "Adejare.544$$"
} 
]
}

// CREATE ADMIN USER
POST http://localhost:3000/api/v1/users/create-admin
Content-Type: application/json

{
    "firstName": "Baami",
    "lastName": "Ademi",
    "username": "adebam",
    "email": "adebam@gmail.com",
    "password": "Adetomi.544$$"
}