// GET USERS
GET http://localhost:3000/api/v1/users?page=1&limit=5
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZTcwOGQwYy1mODdjLTRkODctOTlhYy1hMDg1MjE5NDM1OTYiLCJlbWFpbCI6InRvbWlsb2xhYWFhYUBnbWFpbC5jb20iLCJpYXQiOjE3NDQ1Mjc0NDksImV4cCI6MTc0NDUzMTA0OSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.P5SwdFpxCFd6aOwfOHN-wVViD9h2JfmGCSiJLN6wg5w

// GET A SINGLE USER
GET http://localhost:3000/api/v1/users/6e708d0c-f87c-4d87-99ac-a08521943596
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZTcwOGQwYy1mODdjLTRkODctOTlhYy1hMDg1MjE5NDM1OTYiLCJlbWFpbCI6InRvbWlsb2xhYWFhYUBnbWFpbC5jb20iLCJpYXQiOjE3NDQ1Mjc0NDksImV4cCI6MTc0NDUzMTA0OSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.P5SwdFpxCFd6aOwfOHN-wVViD9h2JfmGCSiJLN6wg5w