// LOGIN USER
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "tomilolaaaaa@gmail.com",
    "password": "Opeyemi.544$$"
}

// LOG OUT USER FROM A SINGLE SESSION
POST http://localhost:3000/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNjIwZjY1Yi03Yzk5LTQzZGYtYjNkNi0wMDdmMGIzMmJmY2UiLCJlbWFpbCI6Im5pY2VtYW5AZ21haWwuY29tIiwiaWF0IjoxNzQ0MjcwMjIwLCJleHAiOjE3NDQyNzM4MjAsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMCJ9.7qOBmfOHtOkWNWJSICnIYLnI_aN4-R7C8TX4o--_Y4M

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNjIwZjY1Yi03Yzk5LTQzZGYtYjNkNi0wMDdmMGIzMmJmY2UiLCJpYXQiOjE3NDQyNjc1MDQsImV4cCI6MTc0NDM1MzkwNCwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.NDtTgk2Tbe3ZK720sr7kLpNDkluFNh4bm2ziX1GyO7U"
}

// LOG OUT USER FROM ALL SESSIONS
POST http://localhost:3000/api/v1/auth/logout-all-sessions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNjIwZjY1Yi03Yzk5LTQzZGYtYjNkNi0wMDdmMGIzMmJmY2UiLCJlbWFpbCI6Im5pY2VtYW5AZ21haWwuY29tIiwiaWF0IjoxNzQ0MjgyMzE0LCJleHAiOjE3NDQyODU5MTQsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMCJ9.jPafUBX0ovOzIlRNir4AGkltZ_Ye1-zT7GzAFJTWUCk

// GET AN ACCESS TOKEN USING THE USER REFRESH TOKEN
POST  http://localhost:3000/api/v1/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNjIwZjY1Yi03Yzk5LTQzZGYtYjNkNi0wMDdmMGIzMmJmY2UiLCJpYXQiOjE3NDQyNjc1MDQsImV4cCI6MTc0NDM1MzkwNCwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.NDtTgk2Tbe3ZK720sr7kLpNDkluFNh4bm2ziX1GyO7U"
}

// FORGOT PASSWORD
POST http://localhost:3000/api/v1/auth/forgot-password
Content-Type: application/json

{
    "email": "tomilolaaaaa@gmail.com"
}

// REST PASSWORD
POST http://localhost:3000/api/v1/auth/reset-password
Content-Type: application/json

{
    "email": "tomilolaaaaa@gmail.com",
    "token": "7bpg0474jts1c7da362fmd",
    "password": "Opeyemi.544$$"
}

// VERIFY EMAIL
POST http://localhost:3000/api/v1/auth/verify-email
Content-Type: application/json

{
    "token": "ieg1izvsf6i8tvq5rvopck",
    "userId": "6e708d0c-f87c-4d87-99ac-a08521943596"
}

// RESEND VERIFY EMAIL
POST http://localhost:3000/api/v1/auth/resend-email-verification
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZTcwOGQwYy1mODdjLTRkODctOTlhYy1hMDg1MjE5NDM1OTYiLCJlbWFpbCI6InRvbWlsb2xhYWFhYUBnbWFpbC5jb20iLCJpYXQiOjE3NDQ0NDc1OTEsImV4cCI6MTc0NDQ1MTE5MSwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.Ot_atxrbmnmAyhYVdv00cfRQoLyjyUmRBrsMIHuF7uQ